import localFont from "next/font/local";
import "./globals.css";

const comic = localFont({
  src: [
    {
      path: '../public/font/Talk-Comic.ttf',
      weight: '400',
      style: 'normal', // Optionally specify style
    },
  ],
  variable: '--font-comic',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comic.variable} font-comic`}>{children}</body>
    </html>
  );
}
